### ISSUE TITLE
Not working on Google?

### ISSUE THREAD

**Issue by BoboTiG** [sharmalay/canvas_capture#11]
For instance, that would be awesome to record such animation: https://www.google.com/search?q=(x^3)y+%2B+(y^3)x
But as soon as I click on "record", a popup tells there is an error.

**Comment by nano-shino** [comment]
It works for me

![image](https://github.com/chaseleslie/canvas_capture/assets/34665904/829a9f4c-f23c-4de0-a137-8d8b6be01524)

**Comment by BoboTiG** [comment]
You are right. I tested again on Chromium, and it works :champagne:
