### ISSUE TITLE
Interface disappears/freezes after multiple uses

### ISSUE THREAD

**Issue by PyroSamurai** [sharmalay/canvas_capture#7]
Similar to issue #5 after I've taken a few captures, the number of times varies, the interface will disappear or freeze up and I have to disable and re-enable it to get it to run again (losing my capture settings). If I change the content of the page I'm on, it also causes error in recording resulting in the same work-around needing to be done.

I wish I could be more specific to what the actual problem is, but I don't know the cause of it not working. It may be a faulty loop or trash collection. Or maybe the add-on wasn't designed to deal with multiple uses. It is not caused by resizing though. I can confirm that the resizing bug in issue #5 exists and I avoid it.

The app itself does its job very well, grabbing the original canvas source and not using a screen capture. Much higher resolution that way. The majority of problems I've had with this app are interface related bugs. If those can be ironed out, I'm sure the app will be much more popular. Thanks for making it, I'm sure I'm the first of many people who will star this repo.

**Comment by sharmalay** [comment]
The upcoming 1.2.0 release adds the ability to list the previously captured videos. I think taking multiple captures (and having the resulting blobs floating around in memory) might be frustrating the browser and causing this issue. With the new interface you can delete old captures after downloading them so they don't pile up.

If this doesn't help, feel free to open a new issue describing the steps to reproduce (as best you can) and your browser version and OS.
