### ISSUE TITLE
More usability

### ISSUE THREAD

**Issue by ven-til** [sharmalay/canvas_capture#8]
More usability:
• Add option to change default "Timeout", "Delay", "FPS" and "Bits Per Second" or keep last input data
• Add button - "capture after refresh page"
• Auto open aftre refresh page

Thank a lot.

**Comment by sharmalay** [comment]
Thanks for the feedback.

I'll add the ability to save the settings or keep them from last use.

As for capturing after page refresh, I will try to figure out a sane way to do this.

Opening after page refresh shouldn't be a problem to implement.
